kind: Service
apiVersion: v1
metadata:
  name: spring-app-back-service
  labels:
    app: spring-app-back
spec:  
  ports:
  - name: spring-app-back
    port: 9090
    nodePort : 30780
  type: NodePort
  selector:
   app: spring-app-back